### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by OmgImAlexis** [brimstone/caddy-consul#1]
Any chance you could add some docs to this? I'd like to try it out and I don't know golang enough to just read the code.

**Comment by brimstone** [comment]
I've had the email about this issue in my inbox for the last 3 year and have thought about it from time to time. Sadly, I haven't had time fulfill the request and I'm sure you've moved on from this project by now. Since Caddy 2 is out, I haven't put forth the effort to verify this plugin works with Caddy 2. I'll archive this repo to show its state. Again, I'm sorry I didn't get to this sooner.
